/** @module knexpress */

exports.KNEX_IGNORED_STATIC_METHODS = [
  'Promise',
  'from',
  'fromJS',
  'into',
  'table',
  'queryBuilder',
  'raw',
  'batchInsert',
  'transaction',
  'initialize',
  'destroy',
  'setMaxListeners',
  'getMaxListeners',
  'emit',
  'addListener',
  'on',
  'once',
  'removeListener',
  'removeAllListeners',
  'listeners',
  'listenerCount',
];
